### ISSUE TITLE
Add .-epub-media-overlay-active to screen.css and epub.css

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/electric-book-workflow#6]
To allow for future sync with audio/SMIL, add styling for -epub-media-overlay-active. e.g.

``` css
.-epub-media-overlay-active {
   background-color: #FFFF99;
}
```
